### ISSUE TITLE
DynamicForms NOT available from Thor CFU

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/DynamicForms#1]
@DougHennig 

I have just noticed that DF is not available from CFU.

I think it's a problem with the version file but am guessing it has never been setup for Deployment.

This is one of those projects that should always be installed, as it happens, and is related to the "Dependencies" discussion in Thor.

**Comment by DougHennig** [comment]
@Jimrnelson A quick glance finds two version files, one of which (_DynamicFormVersionFile.txt) references Matt's GitHub repository instead of this one.

Thor_Update_DynamicForms.prg points to DynamicFormVersionFile.txt in this repository rather than _DynamicFormVersionFile.txt, and DynamicFormVersionFile.txt doesn't specify a download URL.

So, I *think* the fix might be to copy the content of _DynamicFormVersionFile.txt to DynamicFormVersionFile.txt, fix the link so it  points to this repository, and then delete _DynamicFormVersionFile.txt so there aren't two of them.

**Comment by Jimrnelson** [comment]
That was quick! --  I'll give that a try later this afternoon.

**Comment by Jimrnelson** [comment]
@DougHennig 
 
Doug -- it looks like the like to the version file was badly formed.  Slightly different syntax when it's not in a sub-folder.

It's fixed (I think), but can't really test it until I update Thor this weekend.

**Comment by Jimrnelson** [comment]
@DougHennig 

I was a little too optimistic ... the links in the version file were never updated either and there is no zip file.  

This will take a little more effort than anticipated.

**Comment by Jimrnelson** [comment]
Fixed.
